skip_tags: true
image: Visual Studio 2019 Preview

install:
  - cmd: choco install gitversion.portable --version 5.0.1 -y
  - cmd: choco install dotnetcore-sdk --pre

before_build:
  - ps: gitversion /l console /output buildserver

build:
  verbosity: detailed
build_script:
- cmd: dotnet restore src --disable-parallel
- cmd: dotnet build src -c Release --disable-parallel
- cmd: dotnet pack src -c Release --output %APPVEYOR_BUILD_FOLDER%/artifacts/
artifacts:
- path: artifacts/*
deploy:
  provider: NuGet
  api_key:
    secure: u8JpW5kkti8pMi+ra2QcXTJPhkHCA8pkKSiiZOJbcS/vFVHNvF3W8qw1Fy2If6a7
  skip_symbols: false
  artifact: /.*\.nupkg/
